version: '3.8'

services:
  mysql:
    image: mysql_public_data_ingestor
    container_name: mysql_test
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    ports:
      - "3306:3306"
